name: CoReScreen
version: '1.0'
main: me.overlight.corescreen.CoReScreen
author: _OverLight_
softdepend: [PlaceholderAPI]
commands:
  vanish:
    aliases: [v]
  freeze:
    aliases: [f]
  profiler:
    aliases: [p]
  test:
    aliases: [t]